### PR TITLE
set up clean code rules

### PR DESCRIPTION
**Pull request by Westc13**
Created a new repo to hold the README.md for clean code rules.

### CODE REVIEW

**Comment by Westc13** [comment]
Please review the new repo and the contents of README.md.

**Review by chunloy — APPROVED** [review]
Looks good to me!

**Review by yhus — APPROVED** [review]
👍 

On the 88 char rule, is that already reflected in the formatter settings?

**Comment by Westc13** [comment]
@yhus to answer your question: yes the 88 char rule is already reflected in the formatter settings.

**Pull request merged**
